#!/bin/busybox sh
# Minimal init for initramfs using busybox

export PATH=/bin:/usr/bin:/sbin:/usr/sbin

# Mount essential pseudo-filesystems (use busybox applets explicitly)
exec /bin/busybox sh -c '
  /bin/busybox mount -t proc  proc /proc
  /bin/busybox mount -t sysfs sys  /sys
  /bin/busybox mount -t devtmpfs dev /dev

  # hand off to a shell (PID 1)
  exec /bin/busybox sh
'
